### ISSUE TITLE
Adding a location from map, store location name only in locationRemarks

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#68]
We should avoid users to add official location names, to avoid errors. Manually added location names to the locationRemarks field only

**Comment by andersfi** [comment]
should in the case of user input be added as ["verbatimLocality"](http://rs.tdwg.org/dwc/terms/verbatimLocality). The term currently lacking in the location table (but could easily be added). May actually be quite useful since the original description of the locality may contain information lost in translation to official naming.

**Comment by svoboond** [comment]
I added column "verbatimLocality" (text) to the location table.
